-- LAP equipment · schema iniziale
create extension if not exists pgcrypto;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  position integer not null default 0,
  active boolean not null default true
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  slug text not null unique,
  name text not null,
  short_description text,
  description text,
  price_day numeric(10,2) not null default 0,
  deposit numeric(10,2) not null default 0,
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.product_units (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  asset_code text not null unique,
  serial_number text,
  status text not null default 'available' check (status in ('available','maintenance','retired')),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  document_notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.reservations (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique,
  customer_id bigint references public.customers(id) on delete set null,
  start_date date not null,
  end_date date not null,
  status text not null default 'requested' check (status in ('requested','confirmed','picked_up','returned','cancelled')),
  notes text,
  created_at timestamptz not null default now(),
  constraint reservation_dates_valid check (end_date >= start_date)
);

create table if not exists public.reservation_items (
  id bigint generated by default as identity primary key,
  reservation_id uuid not null references public.reservations(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  price_day numeric(10,2) not null,
  unique(reservation_id, product_id)
);

create table if not exists public.unit_assignments (
  id bigint generated by default as identity primary key,
  reservation_item_id bigint not null references public.reservation_items(id) on delete cascade,
  product_unit_id bigint not null references public.product_units(id) on delete restrict,
  unique(reservation_item_id, product_unit_id)
);

create table if not exists public.availability_blocks (
  id bigint generated by default as identity primary key,
  product_unit_id bigint not null references public.product_units(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  reason text,
  created_at timestamptz not null default now(),
  constraint block_dates_valid check (end_date >= start_date)
);

create or replace function public.get_product_availability(
  p_product_id bigint,
  p_start_date date,
  p_end_date date
) returns integer
language sql
stable
as $$
  with total as (
    select count(*)::integer as qty
    from public.product_units u
    where u.product_id = p_product_id
      and u.status = 'available'
      and not exists (
        select 1
        from public.availability_blocks b
        where b.product_unit_id = u.id
          and daterange(b.start_date, b.end_date, '[]') && daterange(p_start_date, p_end_date, '[]')
      )
  ), booked as (
    select coalesce(sum(ri.quantity), 0)::integer as qty
    from public.reservation_items ri
    join public.reservations r on r.id = ri.reservation_id
    where ri.product_id = p_product_id
      and r.status in ('confirmed','picked_up')
      and daterange(r.start_date, r.end_date, '[]') && daterange(p_start_date, p_end_date, '[]')
  )
  select greatest(0, total.qty - booked.qty) from total, booked;
$$;

create index if not exists idx_units_product on public.product_units(product_id);
create index if not exists idx_reservation_items_product on public.reservation_items(product_id);
create index if not exists idx_reservations_dates on public.reservations(start_date, end_date);

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_units enable row level security;

-- Catalogo pubblico: solo lettura dei prodotti e categorie attive.
drop policy if exists "public read active categories" on public.categories;
create policy "public read active categories" on public.categories for select using (active = true);

drop policy if exists "public read active products" on public.products;
create policy "public read active products" on public.products for select using (active = true);

-- Le unità fisiche NON vengono esposte pubblicamente: disponibilità via RPC/API server.

insert into public.categories (slug, name, position) values
('camere','Camere',1),('ottiche','Ottiche',2),('audio','Audio',3),('luci','Luci',4),('video','Video',5),('live','Live',6),('accessori','Accessori',7)
on conflict (slug) do nothing;
